apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: suraj
  labels:
    project: suraj
    component: db
    env: dev

spec:
  selector:
    matchLabels:
      project: suraj
      component: db
      env: dev
  serviceName: "mongodb"
  replicas: 3
  template:
    metadata:
      labels:
        project: suraj
        component: db
        env: dev
    spec:
      containers:
      - name: mongodb
        image: 296062550816.dkr.ecr.us-east-1.amazonaws.com/suraj/dev/mongodb:1.0
        imagePullPolicy: Always
        volumeMounts: # Corrected indentation: inside 'containers'
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "suraj-sc"
      resources:
        requests:
          storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: suraj

spec:
  clusterIP: None #headless service
  selector:
    project: suraj
    component: db
    env: dev
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017
    targetPort: 27017